#!/bin/bash

# Check for Homebrew
if [[ ! "$(type -P brew)" ]]; then
  echo "  Installing Homebrew for you."
  true | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

# Exit if, for some reason, Homebrew is not installed.
[[ ! "$(type -P brew)" ]] && echo "Homebrew failed to install." && return 1

doctor() {
  brew doctor
}
install() {
  brew install "$@"
}
update() {
  brew update
}
upgrade() {
  brew upgrade
}
tap() {
  brew tap "$@"
}
linkapps() {
  brew linkapps
}
cleanup() {
  brew cleanup
}
cask() {
  brew cask "$@"
}
prune(){
  brew prune
}
link(){
    brew link "$@"
}

if [ $# -gt 0 ]; then
  source "$1"
else
  source ./Brewfile
fi


sudo chown root:wheel /usr/local/Cellar/htop-osx/*/bin/htop
sudo chmod u+s /usr/local/Cellar/htop-osx/*/bin/htop

sudo cp -Rf "$(brew --prefix)/opt/osxfuse/Library/Filesystems/osxfusefs.fs" /Library/Filesystems
sudo chmod +s /Library/Filesystems/osxfusefs.fs/Support/load_osxfusefs
